# We should create an Open Babel implementation of pipeline_utils that handles the basic I/O for
# structure files so that the dependency on RDKit can be removed.
# See https://github.com/InformaticsMatters/pipelines-obabel/issues/1

FROM informaticsmatters/deep-app-ubuntu-1604:latest
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

USER root

# Copy the obabel pipeline implementation into the image
COPY src/python /opt/python-obabel
RUN pip3 install im-pipelines-utils==2.4.* &&\
  pip3 install -e /opt/python-obabel

ENTRYPOINT ["bash", "execute"]
